# This file is autogenerated by the repository at https://github.com/gocd/gocd-docker-agent.
# Please file any issues or PRs at https://github.com/gocd/gocd-docker-agent

FROM centos:7
MAINTAINER GoCD <go-cd-dev@googlegroups.com>

ARG GO_WORKING_DIR="/go"
ARG VOLUME_DIR="/godata"

ARG GOCD_VERSION="17.2.0"
ARG DOWNLOAD_URL="https://download.gocd.io/binaries/17.2.0-4587/generic/go-agent-17.2.0-4587.zip"

ADD ${DOWNLOAD_URL} /tmp/go-agent.zip
ADD https://github.com/krallin/tini/releases/download/v0.14.0/tini-static-amd64 /usr/local/sbin/tini

RUN chmod 755 /usr/local/sbin/tini && \
  yum install -y java-1.8.0-openjdk-headless git mercurial subversion openssh-clients bash unzip && \
# unzip the zip file into /go-agent, after stripping the first path prefix
  unzip /tmp/go-agent.zip -d / && \
  mv go-agent-${GOCD_VERSION} /go-agent && \
# Exposing volumes in a simple manner, and setup links behind-the-scenes
# to match GoCD's directory structure
  mkdir -p ${GO_WORKING_DIR} && \
  mkdir -p ${VOLUME_DIR}/pipelines && \
  ln -sf ${VOLUME_DIR}/pipelines ${GO_WORKING_DIR}/pipelines && \
  mkdir -p ${VOLUME_DIR}/config && \
  ln -sf ${VOLUME_DIR}/config ${GO_WORKING_DIR}/config && \
  useradd -m go && \
  chown -R go:go ${VOLUME_DIR} ${GO_WORKING_DIR}

ADD start-agent.sh /go-agent/start-agent.sh

# allow mounting ssh keys, dotfiles, and the go server config and data
VOLUME ["/home/go", "${VOLUME_DIR}"]

USER go
ENTRYPOINT ["/usr/local/sbin/tini", "--"]
WORKDIR ${GO_WORKING_DIR}
ENV AGENT_WORK_DIR=${GO_WORKING_DIR}
ENV STDOUT_LOG_FILE=${GO_WORKING_DIR}/logs/go-agent-bootstrapper.out.log
CMD ["/go-agent/start-agent.sh"]
